Scholarship/Controllers/ComingSoonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Scholarship.Controllers
{
    public class ComingSoonController : Controller
    {
        // GET: ComingSoon
        public ActionResult Index()
        {
            return View();
        }
    }
}

Scholarship/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Scholarship.Controllers
{
    public class FAQController : Controller
    {
        // GET: FAQ
        public ActionResult Index()
        {
            return View();
        }
    }
}

Scholarship/Controllers/ScholarshipController.cs
using Scholarship.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Scholarship.Controllers
{
    public class ScholarshipController : Controller
    {
        ScholarshipEntities entity = new ScholarshipEntities();
        // GET: Scholarship
        public ActionResult Index()
        {
            var ScholarshipData = entity.tblScholarships.Where(x => x.IsActive == true).ToList();

            return View(ScholarshipData);
        }
        public ActionResult Details(int id)
        {
            var ScholarshipData = entity.tblScholarships.Where(x => x.Id == id).FirstOrDefault();

            return View(ScholarshipData);
        }

        public ActionResult LoginForScholarship(StudentLoginDomain model)
        {
            var data = entity.tblStudentDetails.ToList().Where(x => x.UserName == model.UserName && x.Password == model.Password).FirstOrDefault();
            if (data != null)
            {
                var result = new { ScholarshipId = model.ScholarshipId, ID = data.Id };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(0, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Apply(int id)
        {
            var ScholarshipData = entity.tblScholarships.Where(x => x.Id == id).FirstOrDefault();

            return View(ScholarshipData);
        }

    }
}

Scholarship/Controllers/TermsConditionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Scholarship.Controllers
{
    public class TermsConditionsController : Controller
    {
        // GET: TermsConditions
        public ActionResult Index()
        {
            return View();
        }
    }
}

Scholarship/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Eduxam</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=no">


    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="~/Assests/fonts/icomoon/style.css">

    <link rel="stylesheet" href="~/Assests/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assests/css/jquery-ui.css">
    <link rel="stylesheet" href="~/Assests/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Assests/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Assests/css/owl.theme.default.min.css">

    <link rel="stylesheet" href="~/Assests/css/jquery.fancybox.min.css">

    <link rel="stylesheet" href="~/Assests/css/bootstrap-datepicker.css">

    <link rel="stylesheet" href="~/Assests/fonts/flaticon/font/flaticon.css">

    <link rel="stylesheet" href="~/Assests/css/aos.css">
    <link href="~/Assests/css/jquery.mb.YTPlayer.min.css" media="all" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="~/Assests/css/style.css">
</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

    <div class="site-wrap">

        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>

        <div class="py-2 bg-light">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 d-none d-lg-block">
                        <a href="@Url.Action("Index","FAQ")" class="small mr-3"><span class="icon-question-circle-o mr-2"></span> Have a question?</a>
                        <a href="#" class="small mr-3"><span class="icon-envelope-o mr-2"></span> Info@eduxam.in</a>
                    </div>
                    <div class="col-lg-6 text-right">
                        <a href="@Url.Action("Index","Login")" class="small mr-3"><span class="icon-unlock-alt"></span>&nbsp;Student LogIn</a>
                        <a href="@Url.Action("AdminLogin","Login")" class="small mr-3"><span class="icon-unlock-alt"></span>&nbsp;Admin LogIn</a>
                        <a href="@Url.Action("Index","Register")" class="small btn btn-primary px-4 py-2 rounded-0"><span class="icon-users"></span> Register</a>
                    </div>
                </div>
            </div>
        </div>
        <header class="site-navbar py-4 js-sticky-header site-navbar-target" role="banner">

            <div class="container">
                <div class="d-flex align-items-center">
                    <div class="site-logo">
                        <a href="@Url.Action("Index","Home")" class="d-block">
                            <img src="~/Assests/images/logo1 - Copy.jpeg" alt="Image" class="img-fluid">
                            @*<h3>EduXam</h3>*@
                        </a>
                    </div>
                    <div class="mr-auto">
                        <nav class="site-navigation position-relative text-right" role="navigation">
                            <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                                <li class="active">
                                    <a href="@Url.Action("Index","Home")" class="nav-link text-left">Home</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("About","Home")" class="nav-link text-left">About Us</a>
                                    @*<ul class="dropdown">
                                            <li><a href="@Url.Action("About","Home")">Who We Are</a></li>
                                            <li><a href="@Url.Action("About","Home")">Our vision</a></li>
                                        </ul>*@
                                </li>
                                <li>
                                    <a href="@Url.Action("Index","ComingSoon")" class="nav-link text-left">Admissions</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index","Scholarship")" class="nav-link text-left">Scholarship</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Contact","Home")" class="nav-link text-left">Contact Us</a>
                                </li>
                            </ul>
                        </nav>

                    </div>
                    <div class="ml-auto">
                        <div class="social-wrap">
                            <a target="_blank" href="https://www.facebook.com/Eduxam-107536431783126/"><span class="icon-facebook"></span></a>
                            <a target="_blank" href="https://www.instagram.com/invites/contact/?i=i5lw9fmdwidb&utm_content=nhqvb96"><span class="icon-instagram"></span></a>
                            <a href="#"><span class="icon-linkedin"></span></a>
                            <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black">
                                <span class="icon-menu h3"></span>
                            </a>
                        </div>
                    </div>

                </div>
            </div>

        </header>

        @RenderBody()
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        @*<p class="mb-4"><img src="~/Assests/images/logo.png" alt="Image" class="img-fluid"></p>*@
                        <p class="mb-4">EduXam</p>
                        <p>Future is based on learning, and learning is also rewarding.</p>
                        <p>Learn and master your subjects, it will reward right from the stage of learning.</p>
                        <p>Earn scholarships by just giving our periodic examinations.</p>
                        <p><a href="@Url.Action("About","Home")">Learn More</a></p>
                    </div>

                    <div class="col-lg-6">
                        <h3 class="footer-heading"><span>Contact</span></h3>
                        <ul class="list-unstyled">
                            <li><a href="@Url.Action("Contact","Home")">Help Center</a></li>
                            <li><a href="@Url.Action("Index","FAQ")">FAQ</a></li>
                            <li><a href="@Url.Action("Index","TermsConditions")">Terms & Conditions</a></li>
                            <li><a href="@Url.Action("Index","TermsConditions")">Refund policy</a></li>
                            <li><a href="@Url.Action("Index","TermsConditions")">Privacy Policy</a></li>
                        </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="copyright">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by Shrey ITSolutions
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- loader -->
    <div id="loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#51be78" />
        </svg>
    </div>

    <script src="~/Assests/js/jquery-3.3.1.min.js"></script>
    <script src="~/Assests/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/Assests/js/jquery-ui.js"></script>
    <script src="~/Assests/js/popper.min.js"></script>
    <script src="~/Assests/js/bootstrap.min.js"></script>
    <script src="~/Assests/js/owl.carousel.min.js"></script>
    <script src="~/Assests/js/jquery.stellar.min.js"></script>
    <script src="~/Assests/js/jquery.countdown.min.js"></script>
    <script src="~/Assests/js/bootstrap-datepicker.min.js"></script>
    <script src="~/Assests/js/jquery.easing.1.3.js"></script>
    <script src="~/Assests/js/aos.js"></script>
    <script src="~/Assests/js/jquery.fancybox.min.js"></script>
    <script src="~/Assests/js/jquery.sticky.js"></script>
    <script src="~/Assests/js/jquery.mb.YTPlayer.min.js"></script>
    <script src="~/Assests/js/main.js"></script>

</body>
</html>