Scholarship/Areas/Admin/Controllers/ADQuestionController.cs
using Scholarship.Areas.Admin.Domain;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Scholarship.Areas.Admin.Controllers
{
    public class ADQuestionController : Controller
    {
        // GET: Admin/ADQuestion
        ScholarshipEntities entity = new ScholarshipEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetQuestiondata(int id=0)
        {
            var model = entity.tblQuestions.Where(e=>e.Standard==id).ToList();
            //return View(model);
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Add()
        {
            return View();
        }
        //kenirah
        [HttpPost]
        public ActionResult AddOuestions(List<QuestionInfo> QuestionsDetails)
        {
            var qus = entity.tblQuestions.ToList();
            foreach (var item in QuestionsDetails)
            { 
                tblQuestion model = new tblQuestion();
                model.Standard = item.Standard;
                model.Question = item.Question;
                model.OptionA = item.OptionA;
                model.OptionB = item.OptionB;
                model.OptionC = item.OptionC;
                model.OptionD = item.OptionD;
                model.CorrectAns = item.CorrectAnswer;

                entity.Entry(model).State = EntityState.Modified;
                entity.SaveChanges();
                 
                
            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetbyID(int ID)
        {
            var Employee = entity.tblQuestions.Where(x => x.Id ==ID).FirstOrDefault();
            return Json(Employee, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Update(tblQuestion model)
        {
            var exisitingData = entity.tblQuestions.Where(x => x.Id == model.Id).FirstOrDefault();
            entity.tblQuestions.Add(exisitingData);
            entity.SaveChanges();
            return Json("suceess", JsonRequestBehavior.AllowGet);
        }
        public JsonResult Delete(int ID)
        {
            var exisitingData = entity.tblQuestions.Where(x => x.Id ==ID).FirstOrDefault();
            entity.tblQuestions.Remove(exisitingData);
            entity.SaveChanges();
            return Json("suceess" , JsonRequestBehavior.AllowGet);
        }

    }
}

Scholarship/Areas/Admin/Views/Shared/_AdminLayoutcshtml.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin Dashboard</title>
    --
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- daterange picker -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/plugins/daterangepicker/daterangepicker.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Areas/Admin/Assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Areas/Admin/Assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="~/Areas/Admin/Assets/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="index3.html" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Navbar Search -->
                <li class="nav-item">
                    <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                        <i class="fas fa-search"></i>
                    </a>
                    <div class="navbar-search-block">
                        <form class="form-inline">
                            <div class="input-group input-group-sm">
                                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-navbar" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>

                <!-- Messages Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link"  href="@Url.Action("Logout","../Login")">
                        <span>Logout</span>
                    </a>

                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link"  href="@Url.Action("ChangePwd","Login")">
                        <span>Change Password</span>
                    </a>

                </li>

            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/Areas/Admin/Assets/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">EduXam</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                        <li class="nav-item menu-open">
                            <a href="@Url.Action("Index","Admin/AdminDashbord")" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Dashboard
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","AdStudentDetails")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Student Details
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","AdPaymentDetails")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Payment Details
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Scholarship
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("Index","AdScholarship")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Details</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Add","AdScholarship")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Add</p>
                                    </a>
                                </li>

                            </ul>

                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","ADQuestion")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Add Questions
                                </p>
                            </a>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; @DateTime.Now.Year <a>Shrey ITSolutions</a>.</strong>
            All rights reserved.

        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
    </div>


    <!-- jQuery -->
    <script src="~/Areas/Admin/Assets/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Areas/Admin/Assets/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>$.widget.bridge('uibutton', $.ui.button)</script>
    <!-- Bootstrap 4 -->
    <script src="~/Areas/Admin/Assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/Areas/Admin/Assets/plugins/moment/moment.min.js"></script>

    <!-- DataTables  & Plugins -->
    <script src="~/Areas/Admin/Assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Areas/Admin/Assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Areas/Admin/Assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Areas/Admin/Assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/Areas/Admin/Assets/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Areas/Admin/Assets/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/Areas/Admin/Assets/plugins/jszip/jszip.min.js"></script>
    <script src="~/Areas/Admin/Assets/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/Areas/Admin/Assets/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/Areas/Admin/Assets/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Areas/Admin/Assets/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/Areas/Admin/Assets/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>


    <!-- Tempusdominus Bootstrap 4 -->
    <!-- Summernote -->
    <script src="~/Areas/Admin/Assets/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/Areas/Admin/Assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Areas/Admin/Assets/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Areas/Admin/Assets/plugins/summernote/summernote-bs4.min.js"></script>

    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });

        $(function () {
            // Summernote
            $('#summernote').summernote()

            // CodeMirror
            CodeMirror.fromTextArea(document.getElementById("codeMirrorDemo"), {
                mode: "htmlmixed",
                theme: "monokai"
            });
        })
    </script>
</body>
</html>

Scholarship/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>